
const roleData = {
    "Training and Learning & Development (L&D)": {
      "Leadership & Strategy": [
        "Chief Learning Officer (CLO)",
        "Director of Training and Development",
        "Vice President (VP) of Learning & Development",
        "Head of Learning & Development",
        "Learning and Development Manager",
        "Training Manager",
        "Director of Knowledge & Learning",
        "Talent Development Manager",
        "Training Program Manager",
        "Leadership Development Specialist"
      ],
      "Program Design & Development": [
        "Instructional Designer",
        "Senior Instructional Designer",
        "Instructional Design Manager",
        "Curriculum Designer",
        "Curriculum Manager",
        "Curriculum Consultant",
        "Content Developer",
        "Content Curator",
        "Digital Learning Designer",
        "eLearning Developer",
        "eLearning Manager",
        "Learning Architect",
        "Learning Strategist",
        "Learning Experience Designer",
        "Learning Technologist",
        "Instructional Technologist"
      ],
      "Training Delivery & Facilitation": [
        "Corporate Trainer",
        "Senior Trainer",
        "Training Facilitator",
        "Technical Trainer",
        "IT Trainer",
        "Sales Trainer",
        "Customer Service Trainer",
        "Onboarding Trainer",
        "Subject Matter Expert / Trainer",
        "Apprenticeship Trainer",
        "Training Instructor",
        "Learning Coach",
        "Employee Development Coach"
      ],
      "Coordination, Analysis & Support": [
        "Learning and Development Coordinator",
        "Training Coordinator",
        "L&D Administrator",
        "Training Assistant",
        "Learning & Development Assistant",
        "Learning Systems Coordinator",
        "LMS Administrator (Learning Management System)",
        "Learning & Development Analyst",
        "Workforce Development Coordinator",
        "L&D Project Coordinator",
        "Development Administrator",
        "Program Editor"
      ],
      "Specialist & Consulting Roles": [
        "Learning and Development Business Partner",
        "Learning and Development Consultant",
        "Organizational Development Specialist",
        "Performance Consultant",
        "Capability Consultant",
        "People Development Partner",
        "Culture and Engagement Consultant"
      ],
      "Emerging Roles & Niche Specialisms": [
        "Personal Learning Experience Designer",
        "Learning AI Specialist",
        "Hybrid L&D Facilitator",
        "Talent Development Specialist",
        "Digital Learning Transformation Lead",
        "Knowledge Manager",
        "Learning Product Owner",
        "Learning Operations Lead",
        "Skills Development Partner",
        "Competency Framework Specialist",
        "Digital Learning Experience Manager",
        "Learning Innovation Lead"
      ],
      "Entry-Level Roles": [
        "Training Administrator",
        "L&D Intern",
        "Junior Instructional Designer",
        "Assistant Trainer",
        "Training Support Officer",
        "Learning Delivery Assistant",
        "Junior L&D Consultant"
      ]
    },
    "Manufacturing & Operations": {
      "Production and Operations": [
        "Manufacturing Team Member / Production Operative",
        "Machine Operator",
        "Assembler",
        "Fabricator",
        "Welder",
        "Production Supervisor / Team Leader",
        "Production Planner / Scheduler"
      ],
      "Engineering and Technical Roles": [
        "Manufacturing Engineer",
        "Process Engineer",
        "Design Engineer",
        "Automation Engineer",
        "Robotics Engineer",
        "Robotics Technician",
        "Maintenance Engineer",
        "Maintenance Technician",
        "CNC Machinist",
        "CNC Operator",
        "Industrial Engineering Technician"
      ],
      "Quality Control and Assurance": [
        "Quality Control Inspector",
        "Quality Engineer",
        "Quality Manager"
      ],
      "Supply Chain and Logistics": [
        "Material Handler",
        "Inventory Manager",
        "Supply Chain Manager",
        "Logistician"
      ],
      "Management and Administration": [
        "Plant Manager",
        "Operations Manager",
        "Manufacturing Manager"
      ],
      "Corporate Functions": [
        "Health & Safety Officer",
        "Health & Safety Manager",
        "Human Resources / Personnel",
        "Finance / Accounting",
        "Purchasing / Procurement",
        "R&D Engineer",
        "R&D Manager",
        "Sustainability Manager"
      ]
    },
    "Education": {
      "Teaching & Academic Roles": [
        "Teacher (School Teacher)",
        "University Lecturer",
        "Professor",
        "Teaching Assistant (TA)",
        "Special Educational Needs Coordinator (SENCO)",
        "Cover Supervisor",
        "Substitute Teacher / Supply Teacher",
        "Academic Mentor",
        "Private Tutor",
        "Sports Coach"
      ],
      "Leadership and Administration": [
        "Headteacher / Principal",
        "Deputy Headteacher",
        "Assistant Headteacher",
        "School Business Manager",
        "School Governor"
      ],
      "Administrative Support": [
        "Administrative Staff",
        "Academic Registrar",
        "Course Administrator",
        "Data and Assessment Manager"
      ]
    },
    "Defence": {
      "Royal Navy – Officer Roles": [
        "Warfare Officer",
        "Engineering Officer",
        "Logistics Officer",
        "Medical Officer",
        "Dental Officer",
        "Chaplain"
      ],
      "Royal Navy – Enlisted Roles": [
        "Marine Engineer",
        "Weapons Engineer",
        "Air Engineer",
        "Warfare Specialist",
        "Seaman Specialist",
        "Aircraft Handler",
        "Aircraft Controller",
        "Logistics Assistant",
        "Medical Assistant"
      ],
      "British Army – Officer Roles": [
        "Infantry Officer",
        "Armoured Corps Officer",
        "Royal Engineers Officer",
        "Signals Officer",
        "Intelligence Officer",
        "Logistics Officer",
        "Medical Officer",
        "Dental Officer",
        "Veterinary Officer",
        "Human Resources Officer",
        "Legal Officer",
        "Chaplain"
      ],
      "British Army – Soldier & Specialist Roles": [
        "Infantry Soldier",
        "Armoured Vehicle Operator",
        "Army Air Corps Ground Crew",
        "Artillery Gunner (Royal Artillery)",
        "Combat Engineer",
        "Geospatial Intelligence Specialist",
        "Explosive Ordnance Disposal (EOD) Specialist",
        "Transport Operator",
        "Communications Operator",
        "Cyber Warfare Specialist",
        "Intelligence Analyst",
        "Logistician",
        "Chef / Caterer",
        "Maritime Operator",
        "Equipment Technician",
        "Combat Medical Technician",
        "Biomedical Scientist",
        "Military Police",
        "Driver",
        "Logistic Supply Specialist",
        "Petroleum Operator",
        "Movement Controller",
        "Driver Communications Specialist",
        "Port Operator",
        "Postal and Courier Operator",
        "Ammunition Technician",
        "Operational Hygiene Specialist",
        "Army Diver",
        "Army Photographer",
        "Systems Analyst",
        "Electronic Warfare & Signals Intelligence Operator",
        "Cyber Networks Engineer",
        "Cyber Infrastructure Engineer",
        "Power Engineer"
      ],
      "Royal Air Force – Officer Roles": [
        "Pilot",
        "Weapon Systems Officer",
        "Air Traffic Controller",
        "Aerosystems Engineer Officer",
        "Communications Electronics Engineer Officer",
        "Intelligence Officer",
        "Logistics Officer",
        "Medical Officer",
        "Legal Officer",
        "Human Resources Officer",
        "Media Operations Officer",
        "RAF Regiment Officer",
        "Chaplain"
      ],
      "Royal Air Force – Enlisted Roles": [
        "RAF Regiment Gunner",
        "Aircraft Technician",
        "Cyberspace Communications Specialist",
        "Intelligence Analyst",
        "Linguist",
        "Logistician",
        "RAF Medic",
        "RAF Police",
        "Physical Training Instructor",
        "Survival Equipment Specialist",
        "Weapons Technician",
        "Chef",
        "Photographer",
        "Musician"
      ],
      "Strategic Command Roles": [
        "Cyber Operations Specialist",
        "Intelligence Specialist",
        "Special Forces Operator",
        "Logistics Specialist",
        "Digital / IT Specialist",
        "Defence Medical Services Personnel",
        "Training Specialist",
        "Joint Operations Officer",
        "Director Special Forces",
        "Defence Intelligence Officer",
        "Cyber Intelligence Integration Officer"
      ],
      "Royal Marines": [
        "Royal Marines Commando",
        "Amphibious Warfare Specialist",
        "Mine Warfare Specialist",
        "Submarine Operations Specialist"
      ],
      "MOD Police & Civilian Roles": [
        "Ministry of Defence Police (MDP) Officer",
        "Special Escort Group (SEG) Operative",
        "Personal Secretary",
        "Pay Clerk",
        "Commercial Officer",
        "Commodity Manager",
        "Project Support Officer",
        "Administrative Support Officer",
        "Finance Clerk",
        "Recruitment and Marketing Officer",
        "Course Administrator"
      ]
    },
    "Defence": {
      "Royal Navy – Officer Roles": [
        "Warfare Officer",
        "Engineering Officer",
        "Logistics Officer",
        "Medical Officer",
        "Dental Officer",
        "Chaplain"
      ],
      "Royal Navy – Enlisted Roles": [
        "Marine Engineer",
        "Weapons Engineer",
        "Air Engineer",
        "Warfare Specialist",
        "Seaman Specialist",
        "Aircraft Handler",
        "Aircraft Controller",
        "Logistics Assistant",
        "Medical Assistant"
      ],
      "British Army – Officer Roles": [
        "Infantry Officer",
        "Armoured Corps Officer",
        "Royal Engineers Officer",
        "Signals Officer",
        "Intelligence Officer",
        "Logistics Officer",
        "Medical Officer",
        "Dental Officer",
        "Veterinary Officer",
        "Human Resources Officer",
        "Legal Officer",
        "Chaplain"
      ],
      "British Army – Soldier & Specialist Roles": [
        "Infantry Soldier",
        "Armoured Vehicle Operator",
        "Army Air Corps Ground Crew",
        "Artillery Gunner (Royal Artillery)",
        "Combat Engineer",
        "Geospatial Intelligence Specialist",
        "Explosive Ordnance Disposal (EOD) Specialist",
        "Transport Operator",
        "Communications Operator",
        "Cyber Warfare Specialist",
        "Intelligence Analyst",
        "Logistician",
        "Chef / Caterer",
        "Maritime Operator",
        "Equipment Technician",
        "Combat Medical Technician",
        "Biomedical Scientist",
        "Military Police",
        "Driver",
        "Logistic Supply Specialist",
        "Petroleum Operator",
        "Movement Controller",
        "Driver Communications Specialist",
        "Port Operator",
        "Postal and Courier Operator",
        "Ammunition Technician",
        "Operational Hygiene Specialist",
        "Army Diver",
        "Army Photographer",
        "Systems Analyst",
        "Electronic Warfare & Signals Intelligence Operator",
        "Cyber Networks Engineer",
        "Cyber Infrastructure Engineer",
        "Power Engineer"
      ],
      "Royal Air Force – Officer Roles": [
        "Pilot",
        "Weapon Systems Officer",
        "Air Traffic Controller",
        "Aerosystems Engineer Officer",
        "Communications Electronics Engineer Officer",
        "Intelligence Officer",
        "Logistics Officer",
        "Medical Officer",
        "Legal Officer",
        "Human Resources Officer",
        "Media Operations Officer",
        "RAF Regiment Officer",
        "Chaplain"
      ],
      "Royal Air Force – Enlisted Roles": [
        "RAF Regiment Gunner",
        "Aircraft Technician",
        "Cyberspace Communications Specialist",
        "Intelligence Analyst",
        "Linguist",
        "Logistician",
        "RAF Medic",
        "RAF Police",
        "Physical Training Instructor",
        "Survival Equipment Specialist",
        "Weapons Technician",
        "Chef",
        "Photographer",
        "Musician"
      ],
      "Strategic Command Roles": [
        "Cyber Operations Specialist",
        "Intelligence Specialist",
        "Special Forces Operator",
        "Logistics Specialist",
        "Digital / IT Specialist",
        "Defence Medical Services Personnel",
        "Training Specialist",
        "Joint Operations Officer",
        "Director Special Forces",
        "Defence Intelligence Officer",
        "Cyber Intelligence Integration Officer"
      ],
      "Royal Marines": [
        "Royal Marines Commando",
        "Amphibious Warfare Specialist",
        "Mine Warfare Specialist",
        "Submarine Operations Specialist"
      ],
      "MOD Police & Civilian Roles": [
        "Ministry of Defence Police (MDP) Officer",
        "Special Escort Group (SEG) Operative",
        "Personal Secretary",
        "Pay Clerk",
        "Commercial Officer",
        "Commodity Manager",
        "Project Support Officer",
        "Administrative Support Officer",
        "Finance Clerk",
        "Recruitment and Marketing Officer",
        "Course Administrator"
      ]
    },